"""create initial database schema

Revision ID: 11f302616e11
Revises:
Create Date: 2026-10-05 18:38:56.456069

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '11f302616e11'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_rooms_status'),
    sa.CheckConstraint('base_price >= 0', name='ck_rooms_base_price_non_negative'),
    sa.CheckConstraint('capacity >= 1', name='ck_rooms_capacity_positive'),
    sa.CheckConstraint('duration > 0', name='ck_rooms_duration_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'client'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'available'"), nullable=False),
    sa.CheckConstraint("status IN ('available', 'blocked')", name='ck_time_slots_status'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_time_slots_ends_after_starts'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time_slot_id', sa.Integer(), nullable=False),
    sa.Column('players', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'CONFIRMED', 'CANCELLED')", name='ck_bookings_status'),
    sa.CheckConstraint('players >= 1', name='ck_bookings_players_positive'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_bookings_active_time_slot', 'bookings', ['time_slot_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'CONFIRMED', 'IN_PROGRESS')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_bookings_active_time_slot', table_name='bookings', postgresql_where=sa.text("status IN ('PENDING', 'CONFIRMED', 'IN_PROGRESS')"))
    op.drop_table('bookings')
    op.drop_table('time_slots')
    op.drop_table('users')
    op.drop_table('rooms')
    # ### end Alembic commands ###
